name: Rust Checks

on: [push, pull_request]

jobs:
  fmt:
    name: cargo check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust @ stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt

    - name: Run cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt --all -- --check

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust @ stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: clippy

    - name: Run cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy -- -D warnings

  test:
    name: cargo test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust @ stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: test

    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test

  udeps:
    name: cargo udeps
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust @ nightly
      run: rustup toolchain install nightly

    - name: Install cargo-udeps
      run: cargo install cargo-udeps --locked

    - name: Run cargo udeps
      uses: actions-rs/cargo@v1
      with:
        command: udeps
